# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title/

# Setup
title:            Samarth Bhaskar
tagline:
description:

author:
  name:           'Samarth Bhaskar'
  url:            https://twitter.com/samarth

#gems:             [jekyll-paginate, jekyll-sitemap]
#paginate:         5

url:              "https://samarthbhaskar.com" 
plugins:          [jekyll-sitemap, jekyll-feed]


# Custom vars

github:
  repo:          https://github.com/samarthbhaskar
