# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:categories/:title

# Setup
title:            Samarth Bhaskar
tagline:
description:

author:
  name:           'Samarth Bhaskar'
  url:            https://twitter.com/samarthbhaskar

gems:             [jekyll-paginate]
paginate:         5

# Custom vars

github:
  repo:          https://github.com/samarthbhaskar
